Repository dazw00110/laravel-diet-catering, pull requests merged in 2025-06, with the labels that each got.

#34 Utworzenie funkcji roli użytkownika aplikacji, pracownika oraz admina
  app/Http/Controllers/RedirectController.php
  app/Http/Middleware/RoleMiddleware.php
  bootstrap/app.php
  resources/views/admin/dashboard.blade.php
  resources/views/client/dashboard.blade.php
  resources/views/staff/dashboard.blade.php
  routes/web.php
Labels: enhancement

#38 11 reset hasła bez podpinania maila token wypisać na konsoli
  app/Http/Controllers/Auth/PasswordResetController.php
  app/Providers/AppServiceProvider.php
  app/Scheduling/ClearExpiredResetTokens.php
  database/migrations/2025_06_02_121520_create_password_resets_table.php
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/layouts/guest.blade.php
  routes/web.php
Labels: enhancement

#39 10 dodanie opcji totp spomky labsotphp
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/Auth/TwoFactorController.php
  app/Http/Middleware/EnsureTotpVerified.php
  app/Models/User.php
  app/Services/TOTPService.php
  database/migrations/2025_06_02_181715_add_totp_secret_to_users_table.php
  resources/views/admin/dashboard.blade.php
  resources/views/auth/2fa_setup.blade.php
  resources/views/auth/2fa_verify.blade.php
  resources/views/client/dashboard.blade.php
  resources/views/components/totp-banner.blade.php
  resources/views/components/totp-debug.blade.php
  resources/views/layouts/app.blade.php
  resources/views/staff/dashboard.blade.php
  routes/web.php
Labels: enhancement

#43 pełna obsługa CRUD zasobu ofert w panelu admina
  app/Http/Controllers/Admin/ProductController.php
  app/Models/Category.php
  app/Models/Product.php
  database/migrations/2025_05_30_154400_create_categories_table.php
  database/migrations/2025_05_30_154500_create_products_table.php
  database/seeders/CategorySeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ProductSeeder.php
  resources/views/admin/products/create.blade.php
  resources/views/admin/products/edit.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/stats/index.blade.php
  routes/web.php
Labels: enhancement

#45 pełna obsługa CRUD zasobu ofert w panelu pracownika
  app/Http/Controllers/Staff/ProductController.php
  resources/views/admin/stats/index.blade.php
  resources/views/staff/orders/index.blade.php
  resources/views/staff/products/edit.blade.php
  resources/views/staff/products/index.blade.php
  routes/web.php
Labels: enhancement

#46 pracownik może ustalić “super promocję last minute”
  app/Http/Controllers/Staff/ProductController.php
  app/Models/Product.php
  database/migrations/2025_05_30_154500_create_products_table.php
  resources/views/staff/products/index.blade.php
  resources/views/staff/products/promotion.blade.php
  routes/web.php
Labels: enhancement

#47 zasób ofert obsługuje dynamiczne obrazki
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Controllers/Staff/ProductController.php
  app/Models/Product.php
  database/migrations/2025_05_30_154500_create_products_table.php
  database/seeders/ProductSeeder.php
  resources/views/admin/products/create.blade.php
  resources/views/admin/products/edit.blade.php
  resources/views/staff/products/edit.blade.php
Labels: enhancement

#51 Poprawa funkcjonowania TOTP
  app/Http/Controllers/Auth/TwoFactorController.php
  database/migrations/2025_06_08_172049_create_password_resets_table.php
Labels: bug

#52 Dokonywanie zakupów przez klienta, obsługa koszyka, dodanie systemów …
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Controllers/Client/CartController.php
  app/Http/Controllers/Client/ClientOrderController.php
  app/Http/Controllers/Client/DashboardController.php
  app/Http/Controllers/Client/OrderController.php
  app/Http/Controllers/Client/ProductController.php
  app/Http/Controllers/OrderController.php
  app/Models/Discount.php
  app/Models/DiscountUser.php
  app/Models/Order.php
  app/Models/Product.php
  app/Models/ProductReview.php
  app/Models/User.php
  database/migrations/2025_05_30_154636_create_orders_table.php
  database/migrations/2025_06_08_180117_add_address_fields_to_orders_table.php
  database/migrations/2025_06_08_180504_create_discount_user_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/DiscountSeeder.php
  database/seeders/OrderSeeder.php
  database/seeders/ProductReviewSeeder.php
  database/seeders/ProductSeeder.php
  resources/defaults/products/default-product.png
  resources/views/client/cart/index.blade.php
  resources/views/client/contact.blade.php
  resources/views/client/dashboard.blade.php
  resources/views/client/orders/index.blade.php
  resources/views/client/products/index.blade.php
  resources/views/layouts/client.blade.php
  routes/web.php
Labels: enhancement

#58 Stworzenie Dashboard w panelu pracownika
  app/Http/Controllers/Staff/OrderController.php
  database/seeders/OrderSeeder.php
  resources/views/staff/dashboard.blade.php
  resources/views/staff/orders/create.blade.php
  resources/views/staff/orders/edit.blade.php
  resources/views/staff/orders/index.blade.php
  resources/views/staff/orders/show.blade.php
  routes/web.php
Labels: enhancement

#60 Zarządzanie zamówieniami przez klienta, Dodanie dashboarda dla Admina…
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Controllers/Client/ClientOrderController.php
  app/Http/Controllers/Staff/OrderController.php
  app/Models/Order.php
  resources/views/admin/dashboard.blade.php
  resources/views/admin/orders/create.blade.php
  resources/views/admin/orders/edit.blade.php
  resources/views/admin/orders/index.blade.php
  resources/views/admin/orders/show.blade.php
  resources/views/client/contact.blade.php
  routes/web.php
Labels: enhancement

#61 kalendarz obowiązywania zakupionych cateringów w panelu klienta
  resources/views/client/orders/index.blade.php
Labels: enhancement

#62 usunięcie zamówienia, jeśli użytkownik usunie konto
  app/Models/Order.php
  database/seeders/DatabaseSeeder.php
  database/seeders/TestCascadeDeleteSeeder.php
Labels: enhancement

#65 landing page + przeglądanie ofert przez użytkownika niezalogowanego …
  app/Http/Controllers/GuestOfferController.php
  app/Http/Controllers/LandingController.php
  resources/views/components/guest-layout.blade.php
  resources/views/guest/offers.blade.php
  resources/views/landing.blade.php
  resources/views/layouts/main.blade.php
  routes/web.php
Labels: enhancement

#66 Edycja klientów z panelu pracownika
  app/Http/Controllers/Staff/UserController.php
  resources/views/layouts/staff.blade.php
  resources/views/staff/users/create.blade.php
  resources/views/staff/users/edit.blade.php
  resources/views/staff/users/form.blade.php
  resources/views/staff/users/index.blade.php
  routes/web.php
Labels: enhancement

#68 Poprawa walidacji i ograniczeń dat w formularzach
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/Staff/OrderController.php
  app/Http/Controllers/Staff/StatsController.php
  app/Http/Controllers/Staff/UserController.php
  resources/lang/en/validation.php
  resources/views/admin/orders/index.blade.php
  resources/views/admin/stats/index.blade.php
  resources/views/admin/users/create.blade.php
  resources/views/auth/register.blade.php
  resources/views/staff/orders/index.blade.php
  resources/views/staff/stats/index.blade.php
  resources/views/staff/users/create.blade.php
Labels: bug

#69 21-w-razie-niezadowolenia-klient-anuluje-catering-i-dostaje-kod-rabatowy
  .gitignore
  app/Http/Controllers/Client/CartController.php
  app/Http/Controllers/Client/ClientOrderController.php
  app/Http/Controllers/Client/ProductController.php
  app/Http/Controllers/Client/ProductReviewController.php
  app/Models/Cancellation.php
  app/Models/Order.php
  app/Models/Product.php
  database/migrations/2025_05_30_160036_create_cancellations_table.php
  database/migrations/2025_06_09_131202_add_cancellation_date_to_cancellations_table.php
  database/seeders/CancellationSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/DiscountSeeder.php
  database/seeders/ProductSeeder.php
  database/seeders/TestCascadeDeleteSeeder.php
  resources/views/auth/register.blade.php
  resources/views/client/cart/index.blade.php
  resources/views/client/contact.blade.php
  resources/views/client/dashboard.blade.php
  resources/views/client/orders/index.blade.php
  resources/views/client/products/index.blade.php
  resources/views/client/reviews/create.blade.php
  resources/views/components/guest-layout.blade.php
  resources/views/guest/offers.blade.php
  resources/views/landing.blade.php
  resources/views/layouts/client.blade.php
  resources/views/layouts/main.blade.php
  resources/views/profile/partials/update-profile-information-form.blade.php
  resources/views/staff/dashboard.blade.php
  resources/views/staff/orders/create.blade.php
  resources/views/staff/orders/index.blade.php
  resources/views/staff/orders/show.blade.php
  resources/views/staff/products/edit.blade.php
  resources/views/staff/stats/index.blade.php
  resources/views/staff/users/form.blade.php
  routes/web.php
  start.bat
  start.sh
Labels: enhancement

#74 Zaktualizowano README oraz zaadaptowano pliki startowe bat oraz sh
  README.md
  docs/img/OrderEdit1.JPG
  docs/img/OrderShow.JPG
  docs/img/accountClient.JPG
  docs/img/accountStaff.JPG
  docs/img/addClient.JPG
  docs/img/addReviewClient.JPG
  docs/img/addedOrder.JPG
  docs/img/addedProductClient.JPG
  docs/img/afterAddClient.JPG
  docs/img/afterDeleteAdmin.JPG
  docs/img/buyAgainClient.JPG
  docs/img/cancelledOrderClient.JPG
  docs/img/cartClient1.JPG
  docs/img/cartClient2.JPG
  docs/img/clearCartClient.JPG
  docs/img/contactClient.JPG
  docs/img/contactClientInfo.JPG
  docs/img/editClient.JPG
  docs/img/editClient2.JPG
  docs/img/emptyCartClient.JPG
  docs/img/erd.JPG
  docs/img/login.JPG
  docs/img/main.JPG
  docs/img/mainAdmin.JPG
  docs/img/mainClient.JPG
  docs/img/mainStaff.JPG
  docs/img/offersClient.JPG
  docs/img/offersGuest.JPG
  docs/img/orderCancellation.JPG
  docs/img/orderClient.JPG
  docs/img/orderCreateStaff.JPG
  docs/img/orderDelete.JPG
  docs/img/orderEdit2.JPG
  docs/img/orderShowDetails.JPG
  docs/img/ordersAdmin.JPG
  docs/img/ordersClient.JPG
  docs/img/ordersStaff.JPG
  docs/img/passwordReset.JPG
  docs/img/productEdit1.JPG
  docs/img/productEdit2.JPG
  docs/img/productPromotion1.JPG
  docs/img/productPromotion2.JPG
  docs/img/productStaff.JPG
  docs/img/profileEditClient.JPG
  docs/img/rabatForReview.JPG
  docs/img/register.JPG
  docs/img/reviewsClient.JPG
  docs/img/staffUsers.JPG
  docs/img/statsPrint.JPG
  docs/img/statsStaff.JPG
  docs/img/totpClient.JPG
  docs/img/usersAdmin.JPG
  resources/views/client/reviews/create.blade.php
  resources/views/guest/offers.blade.php
  routes/web.php
  start.bat
  start.sh
Labels: documentation, refactor
